name: Generate Snake

on:
  schedule:
    # Run every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write  # Grants access to read and write repository contents
  actions: write   # Grants permission to perform actions such as pushing changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Generate the snake gif
      - name: Generate Snake GIF
        uses: Platane/snk@v3.0.0
        with:
          github_user_name: TheKunalBose  # Replace with your GitHub username

      # Step 3: Check if the files are generated (optional)
      - name: List generated files (optional for debugging)
        run: ls -l

      # Step 4: Commit and push the generated files to the output branch
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true

      # Step 5: Deploy to GitHub Pages (optional, if you want to host it)
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
