name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Generate the snake gif
      - uses: Platane/snk@v2.1.0
        id: snake-gif
        with:
          github_user_name: TheKunalBose

      # Check generated files (optional for debugging)
      - name: Check generated files
        run: ls -l

      - run: git status

      - name: Create output branch if not exists
        run: |
          git checkout -b output || git checkout output

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
